=== informationgrid/ingrid-editor/server/src/main/resources/ingrid/schemes/bast/data-collection_bast.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "DataCollectionBast#1.0.0",
  "$ref": "#/definitions/DataCollectionBast",
  "definitions": {
    "DataCollectionBast": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "isAdVCompatible": {
          "type": ["null", "boolean"]
        },
        "isOpenData": {
          "type": ["null", "boolean"]
        },
        "_uuid": {
          "type": "string"
        },
        "_type": {
          "const": "InGridDataCollection"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "alternateTitle": {
          "type": ["null", "string"]
        },
        "parentIdentifier": {
          "type": ["null", "string"]
        },
        "pointOfContact": {
          "type": "array",
          "items": {
            "$ref": "../../../general.schema.json#/definitions/PointOfContact"
          },
          "minItems": 1
        },
        "advProductGroups": {
          "$ref": "../refs/general.schema.json#/definitions/advProductGroups"
        },
        "themes": {
          "$ref": "../refs/general.schema.json#/definitions/themes"
        },
        "spatial": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "references": {
              "type": "array",
              "items": {
                "$ref": "../../../general.schema.json#/definitions/Spatial"
              }
            },
            "description": {
              "type": ["null", "string"]
            },
            "spatialSystems": {
              "type": "array",
              "items": {
                "$ref": "../refs/general.schema.json#/definitions/KeyValue"
              }
            },
            "verticalExtent": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "Datum": {
                  "anyOf": [
                    {
                      "$ref": "../refs/general.schema.json#/definitions/KeyValue"
                    },
                    {
                      "type": "null"
                    }
                  ]
                },
                "maximumValue": {
                  "type": ["null", "number"]
                },
                "minimumValue": {
                  "type": ["null", "number"]
                },
                "unitOfMeasure": {
                  "anyOf": [
                    {
                      "$ref": "../refs/general.schema.json#/definitions/KeyValue"
                    },
                    {
                      "type": "null"
                    }
                  ]
                }
              }
            }
          },
          "required": []
        },
        "temporal": {
          "$ref": "../refs/general.schema.json#/definitions/temporal"
        },
        "dataset": {
          "$ref": "../refs/general.schema.json#/definitions/dataset"
        },
        "extraInfo": {
          "$ref": "../refs/general.schema.json#/definitions/extraInfo"
        },
        "metadata": {
          "$ref": "../refs/general.schema.json#/definitions/metadata"
        },
        "resource": {
          "$ref": "../refs/general.schema.json#/definitions/resource"
        },
        "keywords": {
          "$ref": "../refs/general.schema.json#/definitions/keywords"
        },
        "maintenanceInformation": {
          "$ref": "../refs/general.schema.json#/definitions/maintenanceInformation"
        },
        "references": {
          "$ref": "../refs/general.schema.json#/definitions/references"
        },
        "graphicOverviews": {
          "$ref": "../refs/general.schema.json#/definitions/graphicOverviews"
        },
        "digitalTransferOptions": {
          "$ref": "../refs/general.schema.json#/definitions/digitalTransferOptions"
        },
        "categoryCatalog": {
          "$ref": "../refs/general.schema.json#/definitions/categoryCatalog"
        },
        "distribution": {
          "$ref": "../refs/general.schema.json#/definitions/distribution"
        },
        "databaseContent": {
          "$ref": "../refs/general.schema.json#/definitions/databaseContent"
        },
        "explanation": {
          "$ref": "../refs/general.schema.json#/definitions/explanation"
        },
        "methodText": {
          "$ref": "../refs/general.schema.json#/definitions/methodText"
        },
        "orderInfo": {
          "$ref": "../refs/general.schema.json#/definitions/orderInfo"
        },
        "openDataCategories": {
          "type": "array",
          "items": {
            "$ref": "../../../general.schema.json#/definitions/KeyValue"
          }
        }
      },
      "required": [
        "_uuid",
        "_type",
        "title",
        "description",
        "pointOfContact",
        "temporal",
        "metadata",
        "dataset"
      ],
      "title": "DataCollection"
    }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/data-collection.minimal.json
{
  "_uuid": "d967e83f-5336-4207-960c-3a6a900d0210",
  "_type": "InGridDataCollection",
  "title": "aba",
  "themes": [],
  "dataset": { "languages": ["142"] },
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Auma, Auma-Weidatal, Greiz, Th√ºringen, 07955, Deutschland (town)",
        "value": {
          "lat1": 50.6587079,
          "lat2": 50.7387079,
          "lon1": 11.8593229,
          "lon2": 11.9393229
        }
      }
    ],
    "spatialSystems": [{ "key": "9000001" }],
    "verticalExtent": { "unitOfMeasure": null }
  },
  "keywords": [],
  "metadata": { "language": { "key": "150" } },
  "resource": { "useConstraints": [], "accessConstraints": [] },
  "temporal": {
    "events": [
      {
        "referenceDate": "2020-12-11T23:00:00.000Z",
        "referenceDateType": { "key": "1" }
      }
    ],
    "status": null,
    "resourceDateType": null
  },
  "extraInfo": { "legalBasicsDescriptions": [] },
  "isOpenData": false,
  "references": [],
  "description": "some description",
  "pointOfContact": [
    { "ref": "826cd85e-9b65-43f6-b2a7-3f20b57450f4", "type": { "key": "11" } }
  ],
  "categoryCatalog": [],
  "databaseContent": [],
  "isAdVCompatible": false,
  "advProductGroups": [],
  "digitalTransferOptions": [],
  "maintenanceInformation": {
    "maintenanceAndUpdateFrequency": null,
    "userDefinedMaintenanceFrequency": { "unit": null }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/data-collection.maximal.json
{
  "_uuid": "a0d1ad6d-4237-4b6e-b0be-cfd072510531",
  "_type": "InGridDataCollection",
  "title": "abab",
  "dataset": { "languages": ["123"] },
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Lederhose, Münchenbernsdorf, Greiz, Thüringen, Deutschland (administrative)",
        "value": {
          "lat1": 50.7910776,
          "lat2": 50.8084996,
          "lon1": 11.8930983,
          "lon2": 11.941834
        }
      }
    ],
    "description": "jhgf",
    "spatialSystems": [{ "key": "9000001" }],
    "verticalExtent": {
      "Datum": { "key": "900005" },
      "maximumValue": 43,
      "minimumValue": 234,
      "unitOfMeasure": { "key": "9001" }
    }
  },
  "keywords": {
    "free": []
  },
  "metadata": { "language": { "key": "65" } },
  "resource": {
    "purpose": "purpose",
    "specificUsage": "use",
    "useLimitation": "constraints",
    "useConstraints": [{ "title": { "key": "18" }, "source": "q" }],
    "accessConstraints": [{ "key": "6" }]
  },
  "temporal": {
    "events": [
      {
        "referenceDate": "2023-02-06T23:00:00.000Z",
        "referenceDateType": { "key": "3" }
      }
    ],
    "status": { "key": "5" },
    "resourceDate": "2023-02-21T23:00:00.000Z",
    "resourceDateType": { "key": "till" }
  },
  "extraInfo": { "legalBasicsDescriptions": [{ "key": "60" }] },
  "orderInfo": "order",
  "isOpenData": false,
  "methodText": "ghjk",
  "references": [
    {
      "url": "https://this.url.ag",
      "type": { "key": "3570" },
      "title": "basis",
      "explanation": "blabla"
    }
  ],
  "description": "asdf",
  "explanation": "ghjk",
  "distribution": {},
  "alternateTitle": "fdsa",
  "pointOfContact": [
    { "ref": "36ec9150-2f1b-4164-8221-08f9a85fc4fb", "type": { "key": "10" } }
  ],
  "categoryCatalog": [
    {
      "date": "2023-02-08T23:00:00.000Z",
      "title": { "key": "1" },
      "edition": "asd"
    }
  ],
  "databaseContent": [{ "moreInfo": "sdfg", "parameter": "rewq" }],
  "isAdVCompatible": true,
  "advProductGroups": [{ "key": "2" }],
  "graphicOverviews": [
    {
      "fileName": {
        "uri": "https://cpyresss.com/rubbish",
        "value": "https://cpyresss.com/rubbish",
        "asLink": true
      },
      "fileDescription": "asdf"
    }
  ],
  "parentIdentifier": "ident",
  "digitalTransferOptions": [
    { "name": { "key": "1" }, "mediumNote": "location", "transferSize": 50 }
  ],
  "maintenanceInformation": {
    "description": "information",
    "maintenanceAndUpdateFrequency": { "key": "8" },
    "userDefinedMaintenanceFrequency": { "unit": { "key": "5" }, "number": 4 }
  }
}
