=== informationgrid/ingrid-editor/server/src/main/resources/uvp/schemes/approval-procedure.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "ApprovalProcedure#1.0.0",
  "$ref": "#/definitions/ApprovalProcedure",
  "definitions": {
    "ApprovalProcedure": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "_uuid": {
          "type": "string",
          "format": "uuid"
        },
        "_type": {
          "const": "UvpApprovalProcedureDoc"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "pointOfContact": {
          "type": "array",
          "items": {
            "$ref": "refs/general.schema.json#/definitions/PointOfContact"
          },
          "minItems": 1,
          "maxItems": 1
        },
        "spatial": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/Spatial"
          },
          "minItems": 1,
          "maxItems": 1
        },
        "receiptDate": {
          "type": "string",
          "format": "date-time"
        },
        "eiaNumbers": {
          "type": "array",
          "items": {
            "$ref": "refs/general.schema.json#/definitions/KeyValue"
          },
          "minItems": 1
        },
        "prelimAssessment": {
          "type": "boolean"
        },
        "processingSteps": {
          "type": "array",
          "items": {
            "$ref": "refs/processing-steps-default.schema.json"
          }
        }
      },
      "required": [
        "_uuid",
        "_type",
        "title",
        "description",
        "pointOfContact",
        "spatial",
        "receiptDate",
        "eiaNumbers",
        "prelimAssessment"
      ],
      "title": "ApprovalProcedure"
    }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/uvp/approval-procedure.wrongStepField.json
{
  "title": "Minimal",
  "_uuid": "87dc26e4-30b2-4956-915c-ad743c325a8c",
  "_type": "UvpApprovalProcedureDoc",
  "description": "Minimales Zulassungsverfahren",
  "pointOfContact": [
    {
      "type": {
        "key": "7"
      },
      "ref": "3c87c74e-ea10-41a5-bc07-93a54396470e"
    }
  ],
  "spatial": [
    {
      "value": {
        "lat1": 50.56928286558243,
        "lon1": 8.613281250000002,
        "lat2": 53.22576843579022,
        "lon2": 13.0078125
      },
      "title": "Neuer Raumbezug",
      "type": "free"
    }
  ],
  "receiptDate": "2022-02-21T23:00:00.000Z",
  "eiaNumbers": [
    {
      "key": "24"
    }
  ],
  "prelimAssessment": true,
  "processingSteps": [
    {
      "type": "publicHearing",
      "publicHearingDate": {
        "start": "2022-03-06T23:00:00.000Z",
        "end": "2022-03-14T23:00:00.000Z"
      },
      "furtherDocs": [
        {
          "title": "schema.txt",
          "downloadURL": {
            "asLink": false,
            "value": "schema.txt",
            "uri": "schema.txt"
          }
        }
      ]
    }
  ]
}
