=== informationgrid/ingrid-editor/server/src/main/resources/uvp/schemes/spatial-or-line.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/SpatialOrLine",
  "definitions": {
    "SpatialOrLine": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "_uuid": {
          "type": "string",
          "format": "uuid"
        },
        "_type": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "publisher": {
          "type": "array",
          "items": {
            "$ref": "refs/general.schema.json#/definitions/Publisher"
          },
          "minItems": 1,
          "maxItems": 1
        },
        "spatial": {
          "type": "array",
          "items": {
            "$ref": "refs/general.schema.json#/definitions/Spatial"
          },
          "minItems": 1
        },
        "receiptDate": {
          "type": "string",
          "format": "date-time"
        },
        "eiaNumbers": {
          "type": "array",
          "items": {
            "$ref": "refs/general.schema.json#/definitions/KeyValue"
          },
          "minItems": 1
        },
        "processingSteps": {
          "type": "array",
          "items": {
            "$ref": "refs/processing-steps-default.schema.json"
          }
        }
      },
      "required": [
        "_uuid",
        "_type",
        "title",
        "description",
        "publisher",
        "spatial",
        "receiptDate",
        "eiaNumbers"
      ],
      "title": "SpatialOrLine"
    }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/uvp/spatial-planning-procedure.minimal.json
{
  "title": "Minimal",
  "_uuid": "87dc26e4-30b2-4956-915c-ad743c325a8c",
  "_type": "UvpSpatialPlanningProcedureDoc",
  "description": "Minimales Raumbezugsverfahren",
  "publisher": [
    {
      "type": {
        "key": "7"
      },
      "ref": "3c87c74e-ea10-41a5-bc07-93a54396470e"
    }
  ],
  "spatial": [
    {
      "value": {
        "lat1": 50.56928286558243,
        "lon1": 8.613281250000002,
        "lat2": 53.22576843579022,
        "lon2": 13.0078125
      },
      "title": "Neuer Raumbezug",
      "type": "free"
    }
  ],
  "eiaNumbers": [
    {
      "key": "24"
    }
  ],
  "receiptDate": "2022-03-06T23:00:00.000Z"
}
