=== informationgrid/ingrid-editor/server/src/main/resources/ingrid/schemes/hmdk/data-collection_hmdk.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "DataCollectionHmdk#1.0.0",
  "$ref": "#/definitions/DataCollectionHmdk",
  "definitions": {
    "DataCollectionHmdk": {
      "allOf": [
        {
          "$ref": "../data-collection.schema.json#/definitions/DataCollection"
        }
      ],
      "properties": {
        "isAdVCompatible": true,
        "hvd": true,
        "hvdCategories": true,
        "isOpenData": true,
        "_uuid": true,
        "_type": true,
        "title": true,
        "description": true,
        "alternateTitle": true,
        "parentIdentifier": true,
        "pointOfContact": true,
        "advProductGroups": true,
        "themes": true,
        "spatial": true,
        "temporal": true,
        "dataset": true,
        "extraInfo": true,
        "metadata": true,
        "resource": true,
        "keywords": true,
        "maintenanceInformation": true,
        "references": true,
        "graphicOverviews": true,
        "digitalTransferOptions": true,
        "categoryCatalog": true,
        "distribution": true,
        "databaseContent": true,
        "explanation": true,
        "methodText": true,
        "orderInfo": true,
        "openDataCategories": true,
        "publicationHmbTG": {
          "type": ["null", "boolean"]
        },
        "informationHmbTG": {
          "type": "array",
          "items": {
            "$ref": "../../../general.schema.json#/definitions/KeyValue"
          }
        }
      },
      "additionalProperties": false
    }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/project.minimal.json
{
  "_uuid": "39ebf57c-9b98-4861-804b-0af30ffdb6c0",
  "title": "project_1",
  "_type": "InGridProject",
  "dataset": { "languages": [] },
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Kahla, Saale-Holzland-Kreis, Th√ºringen, 07768, Deutschland (administrative)",
        "value": {
          "lat1": 50.7883836,
          "lat2": 50.8255522,
          "lon1": 11.5588954,
          "lon2": 11.6105771
        }
      }
    ],
    "spatialSystems": [{ "key": "9000012" }],
    "verticalExtent": { "unitOfMeasure": null }
  },
  "keywords": {
    "free": []
  },
  "metadata": { "language": { "key": "134" } },
  "resource": { "useConstraints": [], "accessConstraints": [] },
  "temporal": {
    "events": [
      {
        "referenceDate": "2020-10-12T22:00:00.000Z",
        "referenceDateType": { "key": "2" }
      }
    ],
    "status": null,
    "resourceDateType": null
  },
  "extraInfo": { "legalBasicsDescriptions": [] },
  "references": [],
  "description": "some random description",
  "pointOfContact": [
    { "ref": "826cd85e-9b65-43f6-b2a7-3f20b57450f4", "type": { "key": "7" } }
  ],
  "isAdVCompatible": false,
  "advProductGroups": [],
  "digitalTransferOptions": [],
  "maintenanceInformation": {
    "maintenanceAndUpdateFrequency": null,
    "userDefinedMaintenanceFrequency": { "unit": null }
  }
}
