=== informationgrid/ingrid-editor/server/src/main/resources/ingrid/schemes/hmdk/publication_hmdk.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "PublicationHmdk#1.0.0",
  "$ref": "#/definitions/PublicationHmdk",
  "definitions": {
    "PublicationHmdk": {
      "allOf": [
        {
          "$ref": "../publication.schema.json#/definitions/Publication"
        }
      ],
      "properties": {
        "isAdVCompatible": true,
        "hvd": true,
        "isOpenData": true,
        "isInspireIdentified": true,
        "_uuid": true,
        "_type": true,
        "title": true,
        "description": true,
        "alternateTitle": true,
        "serviceType": true,
        "serviceUrls": true,
        "serviceVersion": true,
        "parentIdentifier": true,
        "pointOfContact": true,
        "publication": true,
        "advProductGroups": true,
        "themes": true,
        "spatial": true,
        "temporal": true,
        "dataset": true,
        "extraInfo": true,
        "metadata": true,
        "resource": true,
        "keywords": true,
        "maintenanceInformation": true,
        "references": true,
        "graphicOverviews": true,
        "digitalTransferOptions": true,
        "categoryCatalog": true,
        "databaseContent": true,
        "explanation": true,
        "methodText": true,
        "orderInfo": true,
        "distribution": true,
        "openDataCategories": true,
        "publicationHmbTG": {
          "type": ["null", "boolean"]
        },
        "informationHmbTG": {
          "type": "array",
          "items": {
            "$ref": "../../../general.schema.json#/definitions/KeyValue"
          }
        }
      },
      "additionalProperties": false
    }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/information-system.minimal.json
{
  "_uuid": "4e52691b-92b2-4f22-bd13-6ba43edf4ab6",
  "_type": "InGridInformationSystem",
  "title": "info-system",
  "dataset": { "languages": [] },
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Linda, Neustadt an der Orla, Saale-Orla-Kreis, Th√ºringen, Deutschland (administrative)",
        "value": {
          "lat1": 50.6638647,
          "lat2": 50.7090902,
          "lon1": 11.7449969,
          "lon2": 11.8477633
        }
      }
    ],
    "spatialSystems": [{ "key": "9000001" }],
    "verticalExtent": { "unitOfMeasure": null }
  },
  "keywords": {
    "free": []
  },
  "metadata": { "language": { "key": "103" } },
  "resource": { "useConstraints": [], "accessConstraints": [] },
  "temporal": {
    "events": [
      {
        "referenceDate": "2020-12-12T23:00:00.000Z",
        "referenceDateType": { "key": "2" }
      }
    ],
    "status": null,
    "resourceDateType": null
  },
  "extraInfo": { "legalBasicsDescriptions": [] },
  "isOpenData": false,
  "references": [],
  "description": "some more description",
  "serviceType": null,
  "serviceUrls": [],
  "pointOfContact": [
    { "ref": "1f570220-d292-4fd5-8595-e2e088d2f410", "type": { "key": "7" } }
  ],
  "serviceVersion": [],
  "isAdVCompatible": false,
  "advProductGroups": [],
  "isInspireIdentified": false,
  "digitalTransferOptions": [],
  "maintenanceInformation": {
    "maintenanceAndUpdateFrequency": null,
    "userDefinedMaintenanceFrequency": { "unit": null }
  }
}
