=== informationgrid/ingrid-editor/server/src/main/resources/mcloud/schemes/mcloud.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/MCLOUD",
  "definitions": {
    "MCLOUD": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "hasWritePermission": {
          "type": "boolean"
        },
        "hasOnlySubtreeWritePermission": {
          "type": "boolean"
        },
        "_version": {
          "type": "integer"
        },
        "_created": {
          "type": ["string", "null"],
          "format": "date-time"
        },
        "_modified": {
          "type": ["string", "null"],
          "format": "date-time"
        },
        "_state": {
          "type": [
            "string",
            "null"
          ]
        },
        "_id": {
          "type": "string"
        },
        "title": {
          "type": [
            "string",
            "null"
          ],
          "minLength": 1
        },
        "_uuid": {
          "type": "string",
          "format": "uuid"
        },
        "_type": {
          "type": "string"
        },
        "events": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Event"
          }
        },
        "origin": {
          "type": [
            "array",
            "null"
          ]
        },
        "license": {
          "type": [
            "string",
            "null"
          ],
          "minLength": 1
        },
        "spatial": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/Spatial"
          }
        },
        "keywords": {
          "type": "array",
          "items": {
            "type": [
              "string",
              "null"
            ]
          }
        },
        "mfundFKZ": {
          "type": [
            "string",
            "null"
          ]
        },
        "temporal": {
          "$ref": "#/definitions/Temporal"
        },
        "addresses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Address"
          },
          "minItems": 1
        },
        "DCATThemes": {
          "type": "array",
          "items": {
            "type": [
              "string",
              "null"
            ]
          },
          "minItems": 1
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "periodicity": {
          "type": [
            "string",
            "null"
          ],
          "format": "integer"
        },
        "accessRights": {
          "type": [
            "string",
            "null"
          ]
        },
        "mfundProject": {
          "type": [
            "string",
            "null"
          ]
        },
        "distributions": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "$ref": "#/definitions/Distribution"
          },
          "minItems": 1
        },
        "mCloudCategories": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          },
          "minItems": 1
        }
      },
      "required": [
        "_uuid",
        "_type",
        "title",
        "description",
        "addresses",
        "mCloudCategories",
        "DCATThemes",
        "distributions",
        "license"
      ],
      "title": "MCLOUD"
    },
    "Address": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ref": {
          "type": [
            "string",
            "null"
          ]
        },
        "type": {
          "type": [
            "string",
            "null"
          ],
          "format": "integer"
        }
      },
      "required": [
        "ref",
        "type"
      ],
      "title": "Address"
    },
    "Distribution": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "link": {
          "$ref": "#/definitions/Link"
        },
        "type": {
          "type": [
            "string",
            "null"
          ]
        },
        "title": {
          "type": [
            "string",
            "null"
          ]
        },
        "format": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "link",
        "type"
      ],
      "title": "Distribution"
    },
    "Link": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "uri": {
          "type": [
            "string",
            "null"
          ]
        },
        "value": {
          "type": [
            "string",
            "null"
          ]
        },
        "asLink": {
          "type": [
            "boolean",
            "null"
          ]
        }
      },
      "required": [
        "asLink",
        "uri",
        "value"
      ],
      "title": "Link"
    },
    "Event": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "date": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "text": {
          "type": [
            "string",
            "null"
          ],
          "format": "integer"
        }
      },
      "required": [
        "date",
        "text"
      ],
      "title": "Event"
    },
    "Spatial": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": [
            "string",
            "null"
          ]
        },
        "title": {
          "type": [
            "string",
            "null"
          ]
        },
        "value": {
          "$ref": "#/definitions/Value"
        }
      },
      "required": [
        "title",
        "type",
        "value"
      ],
      "title": "Spatial"
    },
    "Value": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "lat1": {
          "type": "number"
        },
        "lat2": {
          "type": "number"
        },
        "lon1": {
          "type": "number"
        },
        "lon2": {
          "type": "number"
        }
      },
      "required": [
        "lat1",
        "lat2",
        "lon1",
        "lon2"
      ],
      "title": "Value"
    },
    "Temporal": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "rangeType": {
          "type": [
            "string",
            "null"
          ]
        },
        "timeSpanDate": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        }
      },
      "required": [
        "rangeType",
        "timeSpanDate"
      ],
      "title": "Temporal"
    }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/mcloud/mcloud.full.json
{
  "title": "mCloudDoc1",
  "_uuid": "96b192b6-987e-4f64-8a37-c752f33a4536",
  "_type": "mCloudDoc",
  "description": "Testbeschreibung",
  "addresses": [
    {
      "ref": "214ca5bf-da1b-4003-b7b6-e73a2ef0ec10",
      "type": {
        "key": "10"
      }
    }
  ],
  "keywords": [
    "eins",
    "zwei",
    "drei"
  ],
  "accessRights": "Nutzung",
  "mCloudCategories": [
    "railway"
  ],
  "DCATThemes": [
    "TRAN"
  ],
  "distributions": [
    {
      "title": "linkTitel",
      "link": {
        "uri": "https://docs.cypress.io/api/this",
        "value": "https://docs.cypress.io/api/this",
        "asLink": true
      },
      "type": {
        "key": "AtomFeed"
      },
      "format": {
        "key": "CSV"
      }
    }
  ],
  "license": {
    "key": "10"
  },
  "origin": "Meine Quelle",
  "mfundProject": "12345",
  "mfundFKZ": "98765",
  "spatial": [
    {
      "value": {
        "lat1": 50.51342652633956,
        "lon1": 8.613281250000002,
        "lat2": 53.22576843579022,
        "lon2": 13.0078125
      },
      "title": "Neuer Raumbezug",
      "type": "free"
    }
  ],
  "events": [
    {
      "date": "2022-01-31T23:00:00.000Z",
      "text": {
        "key": "1"
      }
    },
    {
      "date": "2022-03-15T23:00:00.000Z",
      "text": {
        "key": "3"
      }
    }
  ],
  "temporal": {
    "rangeType": {
      "key": "at"
    },
    "timeSpanDate": "2022-02-07T23:00:00.000Z"
  },
  "periodicity": {
    "key": "10"
  }
}
