=== informationgrid/ingrid-editor/server/src/main/resources/ingrid/schemes/address-organization.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/InGridOrganization",
  "definitions": {
    "InGridOrganization": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "_uuid": {
          "type": "string"
        },
        "_type": {
          "type": "string"
        },
        "title": {
          "type": "string",
          "minLength": 1
        },
        "address": {
          "$ref": "../../general.schema.json#/definitions/AddressClass"
        },
        "contact": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/Contact"
          },
          "minItems": 1
        },
        "organization": {
          "type": ["null", "string"]
        },
        "publishArea": {
          "$ref": "../../general.schema.json#/definitions/KeyValue"
        },
        "positionName": {
          "type": ["null", "string"]
        },
        "hoursOfService": {
          "type": ["null", "string"]
        }
      },
      "required": ["_uuid", "_type", "organization", "contact"],
      "title": "Address"
    }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/mcloud/mcloud-address.full.json
{
  "title": "Published Testorganization",
  "_uuid": "214ca5bf-da1b-4003-b7b6-e73a2ef0ec10",
  "_type": "McloudAddressDoc",
  "address": {
    "city": "Frankfurt",
    "po-box": "ABCDEF",
    "street": "Musterstr. 12",
    "zip-code": "12345",
    "zip-po-box": "98765"
  },
  "contact": [
    {
      "type": {
        "key": "1"
      },
      "connection": "03351464321653"
    },
    {
      "type": {
        "key": "3"
      },
      "connection": "abc@def.gh"
    }
  ],
  "organization": "Published Testorganization"
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/mcloud/mcloud-address.minimal.json
{
  "title": "Published Testorganization",
  "_uuid": "214ca5bf-da1b-4003-b7b6-e73a2ef0ec10",
  "_type": "McloudAddressDoc",
  "address": {
    "city": null,
    "po-box": null,
    "street": null,
    "zip-code": null,
    "zip-po-box": null
  },
  "contact": [
    {
      "type": {
        "key": "1"
      },
      "connection": "03351464321653"
    }
  ],
  "organization": "Published Testorganization"
}
