=== informationgrid/ingrid-editor/server/src/main/resources/ingrid/schemes/geo-service.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "GeoService#1.0.0",
  "$ref": "#/definitions/GeoService",
  "definitions": {
    "GeoService": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "isAdVCompatible": {
          "type": "boolean"
        },
        "isOpenData": {
          "type": "boolean"
        },
        "isInspireIdentified": {
          "type": "boolean"
        },
        "_uuid": {
          "type": "string",
          "format": "uuid"
        },
        "_type": {
          "const": "InGridGeoService"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "alternateTitle": {
          "type": "string"
        },
        "parentIdentifier": {
          "type": "string"
        },
        "pointOfContact": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/PointOfContact"
          },
          "minItems": 1
        },
        "advProductGroups": {
          "$ref": "refs/general.schema.json#/definitions/advProductGroups"
        },
        "themes": {
          "$ref": "refs/general.schema.json#/definitions/themes"
        },
        "spatial": {
          "$ref": "refs/general.schema.json#/definitions/Spatial"
        },
        "temporal": {
          "$ref": "refs/general.schema.json#/definitions/temporal"
        },
        "extraInfo": {
          "$ref": "refs/general.schema.json#/definitions/extraInfo"
        },
        "metadata": {
          "$ref": "refs/general.schema.json#/definitions/metadata"
        },
        "extraInfoPublishArea": {
          "$ref": "../../general.schema.json#/definitions/KeyValue"
        },
        "resource": {
          "$ref": "refs/general.schema.json#/definitions/resource"
        },
        "keywords": {
          "$ref": "refs/general.schema.json#/definitions/keywords"
        },
        "digitalTransferOptions": {
          "$ref": "refs/general.schema.json#/definitions/digitalTransferOptions"
        },
        "distribution": {
          "$ref": "refs/general.schema.json#/definitions/distribution"
        },
        "priorityDatasets": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/KeyValue"
          }
        },
        "spatialScope": {
          "anyOf": [
            { "$ref": "../../general.schema.json#/definitions/KeyValue" },
            { "type": "null" }
          ]
        },
        "maintenanceInformation": {
          "$ref": "refs/general.schema.json#/definitions/maintenanceInformation"
        },
        "references": {
          "$ref": "refs/general.schema.json#/definitions/references"
        },
        "graphicOverviews": {
          "$ref": "refs/general.schema.json#/definitions/graphicOverviews"
        },
        "orderInfo": {
          "$ref": "refs/general.schema.json#/definitions/orderInfo"
        },
        "service": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "type": {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            },
            "version": {
              "type": "array",
              "items": {
                "$ref": "../../general.schema.json#/definitions/KeyValue"
              }
            },
            "operations": {
              "type": "array",
              "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "name": {
                    "$ref": "../../general.schema.json#/definitions/KeyValue"
                  },
                  "methodCall": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                }
              }
            },
            "resolution": {
              "$ref": "refs/general.schema.json#/definitions/resolution"
            },
            "explanation": {
              "type": ["null", "string"]
            },
            "couplingType": {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            },
            "classification": {
              "type": "array",
              "items": {
                "$ref": "../../general.schema.json#/definitions/KeyValue"
              }
            },
            "coupledResources": {
              "$ref": "#/definitions/coupledResources"
            },
            "systemEnvironment": {
              "$ref": "refs/general.schema.json#/definitions/systemEnvironment"
            },
            "hasAccessConstraints": {
              "type": "boolean"
            },
            "implementationHistory": {
              "type": "string"
            }
          }
        },
        "conformanceResult": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "pass": {
                "$ref": "../../general.schema.json#/definitions/KeyValue"
              },
              "isInspire": {
                "type": "boolean"
              },
              "explanation": {
                "type": ["null", "string"]
              },
              "specification": {
                "$ref": "../../general.schema.json#/definitions/KeyValue"
              },
              "publicationDate": {
                "type": "string"
              }
            }
          }
        },
        "openDataCategories": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/KeyValue"
          }
        }
      },
      "required": [
        "_uuid",
        "_type",
        "title",
        "description",
        "pointOfContact",
        "service",
        "spatial",
        "temporal",
        "metadata",
        "resource",
        "extraInfoPublishArea"
      ],
      "title": "GeoService"
    },
    "coupledResources": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "icon": {
                "type": "string"
              },
              "type": {
                "type": "string"
              },
              "uuid": {
                "type": "string"
              },
              "state": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "isExternalRef": {
                "const": false
              }
            }
          },
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "url": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "isExternalRef": {
                "const": true
              }
            }
          }
        ]
      }
    }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/geo-service.minimal.json
{
  "_uuid": "22dcecc1-3eb0-4fa0-839f-14ad4392a7be",
  "title": "geodatendienst_test",
  "_type": "InGridGeoService",
  "themes": [],
  "service": {
    "type": { "key": "1" },
    "version": [],
    "operations": [],
    "resolution": [],
    "couplingType": { "key": "loose" },
    "classification": [{ "key": "303" }],
    "coupledResources": [],
    "hasAccessConstraints": false
  },
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Pausa, Pausa-MÃ¼hltroff, Vogtlandkreis, Sachsen, 07952, Deutschland (town)",
        "value": {
          "lat1": 50.5401795,
          "lat2": 50.6201795,
          "lon1": 11.957094,
          "lon2": 12.037094
        }
      }
    ],
    "spatialSystems": [{ "key": "9000003" }],
    "verticalExtent": { "unitOfMeasure": null }
  },
  "keywords": [],
  "metadata": { "language": { "key": "134" } },
  "resource": {
    "useConstraints": [{ "title": { "key": "10" } }],
    "accessConstraints": []
  },
  "temporal": {
    "events": [
      {
        "referenceDate": "2022-07-11T22:00:00.000Z",
        "referenceDateType": { "key": "1" }
      }
    ],
    "status": null,
    "resourceDateType": null
  },
  "extraInfo": { "legalBasicsDescriptions": [] },
  "isOpenData": false,
  "references": [],
  "description": "descr",
  "distribution": { "format": [] },
  "spatialScope": null,
  "pointOfContact": [
    { "ref": "826cd85e-9b65-43f6-b2a7-3f20b57450f4", "type": { "key": "3" } }
  ],
  "isAdVCompatible": false,
  "advProductGroups": [],
  "priorityDatasets": [],
  "isInspireIdentified": false,
  "extraInfoPublishArea": { "key": "3" },
  "digitalTransferOptions": [],
  "maintenanceInformation": {
    "maintenanceAndUpdateFrequency": null,
    "userDefinedMaintenanceFrequency": { "unit": null }
  }
}
