=== informationgrid/ingrid-editor/server/src/main/resources/ingrid/schemes/information-system.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "InformationSystem#1.0.0",
  "$ref": "#/definitions/InformationSystem",
  "definitions": {
    "InformationSystem": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "isAdVCompatible": {
          "type": "boolean"
        },
        "isOpenData": {
          "type": "boolean"
        },
        "isInspireIdentified": {
          "type": "boolean"
        },
        "_uuid": {
          "type": "string",
          "format": "uuid"
        },
        "_type": {
          "const": "InGridInformationSystem"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "alternateTitle": {
          "type": "string"
        },
        "serviceType": {
          "anyOf": [
            {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "key": {
                  "type": "string"
                }
              }
            },
            {
              "type": "null"
            }
          ]
        },
        "serviceUrls": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "url": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              }
            }
          }
        },
        "serviceVersion": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/KeyValue"
          }
        },
        "parentIdentifier": {
          "type": "string"
        },
        "pointOfContact": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/PointOfContact"
          },
          "minItems": 1
        },
        "advProductGroups": {
          "$ref": "refs/general.schema.json#/definitions/advProductGroups"
        },
        "themes": {
          "$ref": "refs/general.schema.json#/definitions/themes"
        },
        "spatial": {
          "$ref": "refs/general.schema.json#/definitions/Spatial"
        },
        "temporal": {
          "$ref": "refs/general.schema.json#/definitions/temporal"
        },
        "dataset": {
          "$ref": "refs/general.schema.json#/definitions/dataset"
        },
        "extraInfo": {
          "$ref": "refs/general.schema.json#/definitions/extraInfo"
        },
        "metadata": {
          "$ref": "refs/general.schema.json#/definitions/metadata"
        },
        "extraInfoPublishArea": {
          "$ref": "../../general.schema.json#/definitions/KeyValue"
        },
        "resource": {
          "$ref": "refs/general.schema.json#/definitions/resource"
        },
        "keywords": {
          "$ref": "refs/general.schema.json#/definitions/keywords"
        },
        "maintenanceInformation": {
          "$ref": "refs/general.schema.json#/definitions/maintenanceInformation"
        },
        "references": {
          "$ref": "refs/general.schema.json#/definitions/references"
        },
        "graphicOverviews": {
          "$ref": "refs/general.schema.json#/definitions/graphicOverviews"
        },
        "digitalTransferOptions": {
          "$ref": "refs/general.schema.json#/definitions/digitalTransferOptions"
        },
        "categoryCatalog": {
          "$ref": "refs/general.schema.json#/definitions/categoryCatalog"
        },
        "databaseContent": {
          "$ref": "refs/general.schema.json#/definitions/databaseContent"
        },
        "explanation": {
          "$ref": "refs/general.schema.json#/definitions/explanation"
        },
        "methodText": {
          "$ref": "refs/general.schema.json#/definitions/methodText"
        },
        "systemEnvironment": {
          "$ref": "refs/general.schema.json#/definitions/systemEnvironment"
        },
        "baseDataText": {
          "$ref": "refs/general.schema.json#/definitions/baseDataText"
        },
        "history": {
          "type": "string"
        },
        "orderInfo": {
          "$ref": "refs/general.schema.json#/definitions/orderInfo"
        },
        "distribution": {
          "$ref": "refs/general.schema.json#/definitions/distribution"
        },
        "openDataCategories": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/KeyValue"
          }
        }
      },
      "required": [
        "_uuid",
        "_type",
        "title",
        "description",
        "pointOfContact",
        "spatial",
        "temporal",
        "metadata",
        "dataset",
        "extraInfoPublishArea"
      ],
      "title": "InformationSystem"
    }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/information-system.maximal.json
{
  "_uuid": "00cbcb2e-c52f-478d-97a4-46b0f5dabb3a",
  "title": "information_system_max",
  "_type": "InGridInformationSystem",
  "themes": [{ "key": "108" }],
  "dataset": { "languages": ["142"] },
  "history": "history4",
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Gr√ºna, Chemnitz, Sachsen, 09224, Deutschland (administrative)",
        "value": {
          "lat1": 50.801461,
          "lat2": 50.8497718,
          "lon1": 12.7275333,
          "lon2": 12.8191334
        }
      }
    ],
    "description": "locational data",
    "spatialSystems": [{ "key": "4258" }],
    "verticalExtent": {
      "Datum": { "key": "900009" },
      "maximumValue": 6,
      "minimumValue": 7,
      "unitOfMeasure": { "key": "9001" }
    }
  },
  "keywords": ["optional info"],
  "metadata": { "language": { "key": "103" } },
  "resource": {
    "purpose": "production purpose",
    "specificUsage": "use7",
    "useLimitation": "use-constraints5",
    "useConstraints": [{ "title": { "key": "33" }, "source": "src" }],
    "accessConstraints": [{ "key": "4" }]
  },
  "temporal": {
    "events": [
      {
        "referenceDate": "2022-01-11T23:00:00.000Z",
        "referenceDateType": { "key": "2" }
      }
    ],
    "status": { "key": "1" },
    "resourceDate": "2022-06-14T22:00:00.000Z",
    "resourceDateType": { "key": "at" }
  },
  "extraInfo": { "legalBasicsDescriptions": [{ "key": "68" }] },
  "orderInfo": "order data",
  "isOpenData": false,
  "references": [
    {
      "url": "https://this-reference.com/here",
      "type": { "key": "9999" },
      "title": "unspecific reference",
      "explanation": "reference information"
    }
  ],
  "description": "long description",
  "explanation": "remarks",
  "serviceType": { "key": "1" },
  "serviceUrls": [
    {
      "url": "https://service-url.com/somewhere",
      "name": "service-url",
      "description": "more service info"
    }
  ],
  "baseDataText": "basical data",
  "distribution": {},
  "alternateTitle": "short description",
  "pointOfContact": [
    { "ref": "1f570220-d292-4fd5-8595-e2e088d2f410", "type": { "key": "3" } }
  ],
  "serviceVersion": [{ "key": null, "value": "4" }],
  "isAdVCompatible": false,
  "advProductGroups": [{ "key": "14" }],
  "graphicOverviews": [
    {
      "title": "first_archived(2)",
      "fileName": {
        "uri": "first_archived(2).txt",
        "value": "first_archived(2).txt",
        "asLink": false
      }
    }
  ],
  "parentIdentifier": "ident5",
  "systemEnvironment": "system environm",
  "isInspireIdentified": false,
  "extraInfoPublishArea": { "key": "2" },
  "digitalTransferOptions": [
    { "name": { "key": "17" }, "mediumNote": "where", "transferSize": 34 }
  ],
  "maintenanceInformation": {
    "description": "time reference infos",
    "maintenanceAndUpdateFrequency": { "key": "7" },
    "userDefinedMaintenanceFrequency": { "unit": { "key": "5" }, "number": 4 }
  }
}
