=== informationgrid/ingrid-editor/server/src/main/resources/ingrid/schemes/literature.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Literature#1.0.0",
  "$ref": "#/definitions/Literature",
  "definitions": {
    "Literature": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "isAdVCompatible": {
          "type": "boolean"
        },
        "isOpenData": {
          "type": "boolean"
        },
        "isInspireIdentified": {
          "type": "boolean"
        },
        "_uuid": {
          "type": "string",
          "format": "uuid"
        },
        "_type": {
          "const": "InGridLiterature"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "alternateTitle": {
          "type": "string"
        },
        "serviceType": {
          "anyOf": [
            {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "key": {
                  "type": "string"
                }
              }
            },
            {
              "type": "null"
            }
          ]
        },
        "serviceUrls": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "url": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              }
            }
          }
        },
        "serviceVersion": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/KeyValue"
          }
        },
        "parentIdentifier": {
          "type": "string"
        },
        "pointOfContact": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/PointOfContact"
          },
          "minItems": 1
        },
        "publication": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "isbn": {
              "type": "string"
            },
            "pages": {
              "type": "string"
            },
            "author": {
              "type": "string"
            },
            "volume": {
              "type": "string"
            },
            "location": {
              "type": "string"
            },
            "publisher": {
              "type": "string"
            },
            "explanation": {
              "type": "string"
            },
            "publishedIn": {
              "type": "string"
            },
            "baseDataText": {
              "type": "string"
            },
            "documentType": {
              "anyOf": [
                { "$ref": "refs/general.schema.json#/definitions/KeyValue" },
                { "type": "null" }
              ]
            },
            "publicationDate": {
              "type": "string"
            },
            "publishingHouse": {
              "type": "string"
            },
            "bibliographicData": {
              "type": "string"
            },
            "placeOfPublication": {
              "type": "string"
            }
          }
        },
        "advProductGroups": {
          "$ref": "refs/general.schema.json#/definitions/advProductGroups"
        },
        "themes": {
          "$ref": "refs/general.schema.json#/definitions/themes"
        },
        "spatial": {
          "$ref": "refs/general.schema.json#/definitions/Spatial"
        },
        "temporal": {
          "$ref": "refs/general.schema.json#/definitions/temporal"
        },
        "dataset": {
          "$ref": "refs/general.schema.json#/definitions/dataset"
        },
        "extraInfo": {
          "$ref": "refs/general.schema.json#/definitions/extraInfo"
        },
        "metadata": {
          "$ref": "refs/general.schema.json#/definitions/metadata"
        },
        "extraInfoPublishArea": {
          "$ref": "../../general.schema.json#/definitions/KeyValue"
        },
        "resource": {
          "$ref": "refs/general.schema.json#/definitions/resource"
        },
        "keywords": {
          "$ref": "refs/general.schema.json#/definitions/keywords"
        },
        "maintenanceInformation": {
          "$ref": "refs/general.schema.json#/definitions/maintenanceInformation"
        },
        "references": {
          "$ref": "refs/general.schema.json#/definitions/references"
        },
        "graphicOverviews": {
          "$ref": "refs/general.schema.json#/definitions/graphicOverviews"
        },
        "digitalTransferOptions": {
          "$ref": "refs/general.schema.json#/definitions/digitalTransferOptions"
        },
        "categoryCatalog": {
          "$ref": "refs/general.schema.json#/definitions/categoryCatalog"
        },
        "databaseContent": {
          "$ref": "refs/general.schema.json#/definitions/databaseContent"
        },
        "explanation": {
          "$ref": "refs/general.schema.json#/definitions/explanation"
        },
        "methodText": {
          "$ref": "refs/general.schema.json#/definitions/methodText"
        },
        "orderInfo": {
          "$ref": "refs/general.schema.json#/definitions/orderInfo"
        },
        "distribution": {
          "$ref": "refs/general.schema.json#/definitions/distribution"
        }
      },
      "required": [
        "_uuid",
        "_type",
        "title",
        "description",
        "pointOfContact",
        "spatial",
        "temporal",
        "metadata",
        "dataset",
        "extraInfoPublishArea"
      ],
      "title": "Literature"
    }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/literature.maximal.json
{
  "_uuid": "22dcecc1-3eb0-4fa0-839f-14ad4393a7be",
  "title": "literatur_maximal_test",
  "_type": "InGridLiterature",
  "themes": [{ "key": "317" }],
  "dataset": { "languages": ["113"] },
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Hansa, Gremmendorf, Münster-Südost, Münster, Nordrhein-Westfalen, 48155, Deutschland (allotments)",
        "value": {
          "lat1": 51.9419043,
          "lat2": 51.9439881,
          "lon1": 7.6485776,
          "lon2": 7.652429
        }
      }
    ],
    "description": "location-information",
    "spatialSystems": [{ "key": "9000002" }],
    "verticalExtent": {
      "Datum": { "key": "900005" },
      "maximumValue": 8,
      "minimumValue": 7,
      "unitOfMeasure": { "key": "4" }
    }
  },
  "keywords": ["optional-term"],
  "metadata": { "language": { "key": "182" } },
  "resource": {
    "purpose": "purpose1",
    "specificUsage": "use1",
    "useLimitation": "use-constraints",
    "useConstraints": [{ "title": { "key": "2" }, "source": "source-5" }],
    "accessConstraints": [{ "key": "5" }]
  },
  "temporal": {
    "events": [
      {
        "referenceDate": "2022-09-06T22:00:00.000Z",
        "referenceDateType": { "key": "3" }
      }
    ],
    "status": { "key": "7" },
    "resourceRange": {
      "end": "2022-10-30T23:00:00.000Z",
      "start": "2022-10-04T22:00:00.000Z"
    },
    "resourceDateType": { "key": "since" },
    "resourceDateTypeSince": { "key": "exactDate" }
  },
  "extraInfo": { "legalBasicsDescriptions": [{ "key": "39" }] },
  "orderInfo": "order location",
  "isOpenData": false,
  "references": [
    {
      "url": "https://some-url/there",
      "type": { "key": "3535" },
      "title": "keys",
      "explanation": "info remarks"
    }
  ],
  "description": "full-descr",
  "publication": {
    "isbn": "isbn",
    "pages": "pages",
    "author": "author",
    "volume": "vol",
    "location": "location",
    "publisher": "hrsg",
    "explanation": "addition-info",
    "publishedIn": "which",
    "baseDataText": "basis data",
    "documentType": { "key": "2" },
    "publicationDate": "year",
    "publishingHouse": "publisher",
    "bibliographicData": "bibl-info",
    "placeOfPublication": "where"
  },
  "alternateTitle": "short-descr",
  "pointOfContact": [
    { "ref": "36ec9150-2f1b-4164-8221-08f9a85fc4fb", "type": { "key": "8" } }
  ],
  "isAdVCompatible": false,
  "advProductGroups": [{ "key": "13" }],
  "graphicOverviews": [
    {
      "fileName": {
        "uri": "https://some-link-somewhere.com",
        "value": "https://some-link-somewhere.com",
        "asLink": true
      },
      "fileDescription": "url-description"
    }
  ],
  "parentIdentifier": "ident3",
  "extraInfoPublishArea": { "key": "3" },
  "digitalTransferOptions": [
    {
      "name": { "key": "900005" },
      "mediumNote": "storage-location",
      "transferSize": 65
    }
  ],
  "maintenanceInformation": {
    "description": "remarks",
    "maintenanceAndUpdateFrequency": { "key": "1" },
    "userDefinedMaintenanceFrequency": { "unit": { "key": "5" }, "number": 3 }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/literature.minimal.json
{
  "_uuid": "5aaa65dc-e811-40a1-8026-d262b3d9fcf7",
  "title": "literature_5",
  "_type": "InGridLiterature",
  "themes": [],
  "dataset": { "languages": ["247"] },
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Heyda, Waldheim, Mittelsachsen, Sachsen, 04720, Deutschland (village)",
        "value": {
          "lat1": 51.0689498,
          "lat2": 51.1089498,
          "lon1": 13.0815141,
          "lon2": 13.1215141
        }
      }
    ],
    "spatialSystems": [{ "key": "9000003" }],
    "verticalExtent": { "unitOfMeasure": null }
  },
  "keywords": [],
  "metadata": { "language": { "key": "363" } },
  "resource": { "useConstraints": [], "accessConstraints": [] },
  "temporal": {
    "events": [
      {
        "referenceDate": "2020-11-12T23:00:00.000Z",
        "referenceDateType": { "key": "2" }
      }
    ],
    "status": null,
    "resourceDateType": null
  },
  "extraInfo": { "legalBasicsDescriptions": [] },
  "isOpenData": false,
  "references": [],
  "description": "random description",
  "publication": {},
  "pointOfContact": [
    { "ref": "83f92167-6606-4182-948c-5747ad608b80", "type": { "key": "7" } }
  ],
  "isAdVCompatible": false,
  "advProductGroups": [],
  "extraInfoPublishArea": { "key": "3" },
  "digitalTransferOptions": [],
  "maintenanceInformation": {
    "maintenanceAndUpdateFrequency": null,
    "userDefinedMaintenanceFrequency": { "unit": null }
  }
}
